services:
  WapplerSystems\Avif\EventListener\AfterFileProcessing:
    tags:
      - name: event.listener
        identifier: 'avif.after-file-processing'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent
